#!/bin/sh
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Initializing the shell variables with directory names
#


export BASE=$HOME/Documents/prog/rakudo/modules
export THIS_DIR=$BASE/raku-Date-Calendar-Hebrew
